name: Android Build ## name of the workflow

on: [ push ]

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest # using ubuntu latest version / or you can use a specific version

    steps:
      - name: Check out Git repository # clone the repo to local ci workspace
        uses: actions/checkout@v2

      - name: Set up our JDK environment # setup JDK environment: mandatory as we need to build  android project
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Install dependencies # install project deps with --frozen-lockfile to make sure we will have the same packages version ( very recommended  on running yarn install on ci)
        run: yarn install --frozen-lockfile

      - name: Generate App APK
        run: |
          cd android && ./gradlew assembleRelease

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: firebase login:ci --no-localhost
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute ./android/app/build/outputs/apk/release/app-release.apk 
          --app ${{ secrets.FIREBASE_APP_ID }} 
          --groups testers 
          --token ${{ secrets.FIREBASE_TOKEN }}
