name: Build & upload to Firebase App Distribution

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: build release
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: upload artifact to Firebase App Distribution
        uses: nickwph/firebase-app-distribution-action@v1
        with:
          file: app-release.apk
          app: ${{ secrets.FIREBASE_APP_ID }}
          credentials-file: ${{ secrets.CREDENTIAL_FILE_CONTENT }}  # Optional: This is ignored if credentials is defined.
          groups: testers
